import Foundation

/// Uniform-type identifiers Cliplex reads and writes.
public enum UTI {
    public static let text = "public.utf8-plain-text"
    public static let rtf = "public.rtf"
    public static let png = "public.png"
    public static let tiff = "public.tiff"
    public static let fileURL = "public.file-url"
}

/// Pasteboard types that mark a clip as secret / not-to-be-stored
/// (macOS / nspasteboard.org convention).
public let concealedPasteboardTypes: [String] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
]

/// A snapshot of the clipboard captured from the OS.
public struct Captured: Equatable, Sendable {
    public var kind: ClipKind
    public var preview: String
    /// Whether the source marked this clip as concealed / secret / transient.
    public var concealed: Bool
    /// Bundle id / name of the app that produced the clip, if known.
    public var sourceApp: String?
    public var assets: [ClipAsset]

    public init(kind: ClipKind, preview: String, concealed: Bool, sourceApp: String?, assets: [ClipAsset]) {
        self.kind = kind
        self.preview = preview
        self.concealed = concealed
        self.sourceApp = sourceApp
        self.assets = assets
    }

    /// Converts the capture into a ``NewClip`` ready for storage.
    public func toNewClip() -> NewClip {
        NewClip(kind: kind, preview: preview, sourceApp: sourceApp, assets: assets)
    }

    /// Returns true when there is no usable content to store. A clip counts as
    /// empty only when it has no assets, or its sole content is blank text
    /// (clips carrying any non-text asset — image, RTF, files — are never empty).
    public var isEmpty: Bool {
        if assets.isEmpty { return true }
        let hasNonText = assets.contains { $0.uti != UTI.text }
        return !hasNonText && preview.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }
}

/// Configuration for the capture filter.
public struct CaptureConfig: Equatable, Sendable {
    /// Skip clips marked concealed/secret/transient by their source app.
    public var ignoreConcealed: Bool
    /// Bundle ids / app names whose clips should never be stored.
    public var excludedApps: [String]

    public init(ignoreConcealed: Bool = true, excludedApps: [String] = []) {
        self.ignoreConcealed = ignoreConcealed
        self.excludedApps = excludedApps
    }
}

/// Capture filtering: decides whether a captured clip should be stored.
///
/// Keeps the privacy-by-default policy in one pure, well-tested place so the
/// background monitor stays a thin loop.
public func shouldStore(_ captured: Captured, config: CaptureConfig) -> Bool {
    if captured.isEmpty { return false }
    if config.ignoreConcealed && captured.concealed { return false }
    if let app = captured.sourceApp,
       config.excludedApps.contains(where: { $0.caseInsensitiveCompare(app) == .orderedSame }) {
        return false
    }
    return true
}

/// Detects whether a trimmed string is a CSS-style hex color (#RGB or #RRGGBB),
/// used to render a color swatch in the panel.
public func detectHexColor(_ text: String) -> Bool {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard trimmed.first == "#" else { return false }
    let hex = trimmed.dropFirst()
    guard hex.count == 3 || hex.count == 6 else { return false }
    return hex.allSatisfy { $0.isHexDigit }
}
