//! Cliplex platform layer.
//!
//! Defines an OS-agnostic [`ClipboardBackend`] trait for the parts of a
//! clipboard manager that must talk to the operating system:
//!
//! * **Change detection** — a cheap token that changes when the clipboard does.
//! * **Reading** — capture the current clipboard across formats, including a
//!   `concealed` flag for password-manager / secret / transient clips.
//! * **Writing** — put a clip back on the clipboard.
//! * **Active-app detection** — identify the frontmost app (for the
//!   user-configurable exclusion list).
//!
//! A fully native macOS implementation is provided via `NSPasteboard`. Other
//! platforms currently use a portable [`arboard`]-based fallback; native
//! Windows/Linux backends slot in behind the same trait.

use cliplex_core::{ClipAsset, ClipKind, NewClip};

mod backend;
pub use backend::backend;

mod capture;
pub use capture::{should_store, CaptureConfig};

/// Uniform-type identifier used for plain UTF-8 text across platforms.
pub const UTI_TEXT: &str = "public.utf8-plain-text";
/// Uniform-type identifier used for PNG image data.
pub const UTI_PNG: &str = "public.png";

/// Pasteboard types that mark a clip as secret / not-to-be-stored (macOS /
/// nspasteboard.org convention).
pub const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// A snapshot of the clipboard captured from the OS.
#[derive(Debug, Clone)]
pub struct Captured {
    /// Primary kind of the content.
    pub kind: ClipKind,
    /// Searchable plain-text preview.
    pub preview: String,
    /// Whether the source marked this clip as concealed / secret / transient.
    pub concealed: bool,
    /// Bundle id / name of the app that produced the clip, if known.
    pub source_app: Option<String>,
    /// Raw format payloads.
    pub assets: Vec<ClipAsset>,
}

impl Captured {
    /// Converts the capture into a [`NewClip`] ready for storage.
    pub fn into_new_clip(self) -> NewClip {
        NewClip {
            kind: self.kind,
            preview: self.preview,
            source_app: self.source_app,
            assets: self.assets,
        }
    }

    /// Returns true when there is no usable content to store.
    pub fn is_empty(&self) -> bool {
        self.assets.is_empty() || (self.kind == ClipKind::Text && self.preview.trim().is_empty())
    }
}

/// Errors raised by the platform layer.
#[derive(Debug, thiserror::Error)]
pub enum PlatformError {
    /// The operation is not supported on this platform/build yet.
    #[error("operation not supported on this platform")]
    Unsupported,
    /// A backend-specific failure.
    #[error("platform error: {0}")]
    Other(String),
}

/// Result alias for the platform layer.
pub type Result<T> = std::result::Result<T, PlatformError>;

/// Abstraction over OS clipboard access.
pub trait ClipboardBackend: Send {
    /// Returns a token that changes whenever the clipboard content changes.
    ///
    /// Backends use the cheapest signal available (macOS `changeCount`,
    /// Windows clipboard sequence number, or a content hash as a fallback).
    fn change_token(&mut self) -> Result<u64>;

    /// Reads the current clipboard content, or `None` when it is empty.
    fn read(&mut self) -> Result<Option<Captured>>;

    /// Writes the given format payloads to the clipboard.
    fn write(&mut self, assets: &[ClipAsset]) -> Result<()>;

    /// Returns the bundle id / name of the frontmost application, if available.
    fn active_app(&mut self) -> Result<Option<String>>;
}

/// Name of the current target platform, used for diagnostics.
pub fn target_os() -> &'static str {
    std::env::consts::OS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn target_os_known() {
        assert!(!target_os().is_empty());
    }

    #[test]
    fn empty_text_capture_is_empty() {
        let c = Captured {
            kind: ClipKind::Text,
            preview: "   ".into(),
            concealed: false,
            source_app: None,
            assets: vec![ClipAsset {
                uti: UTI_TEXT.into(),
                bytes: b"   ".to_vec(),
                idx: 0,
            }],
        };
        assert!(c.is_empty());
    }

    #[test]
    fn backend_is_constructible() {
        // Constructing the backend must not panic on any platform.
        let _ = backend();
    }
}
